sudo: false
language: cpp

compiler:
  - clang
  - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
			
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  
script:
  - mkdir build
  - cd build
  - cmake

notifications:
  email:
    recipients:
      - stephenberry.developer@gmail.com
    on_success: always
    on_failure: always

