# Site settings
title: Ascent-beta
#email: 
description: > # this means to ignore newlines until "baseurl:"
  Ascent is an open source architecture for time-based simulations. Module and dynamic, with discrete and continuous parameter mixing.
  Easily solve complex systems of differential equations. Ascent performs automatic and dynamic ordering to properly solve dynamic systems.
baseurl: "/ascent-beta" # the subpath of your site
#url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username: stephenberry

# Build settings
markdown: kramdown
